---
- name: copy Datastax repo file
  copy: 
        src=datastax.repo
        dest=/etc/yum.repos.d/
        mode=0644

- name: import rpm key
  rpm_key:
        key=https://rpm.datastax.com/rpm/repo_key
        state=present
- debug:
        msg: added the repo setup, going to install dse {{ dse_version  }} on {{ inventory_hostname }}/{{ ansible_default_ipv4.address }}

- name: install datastax enterprise
  yum:
        name=dse-full-{{ dse_version }}-1
        state=installed
- debug:
        msg: completed dse {{ dse_version  }} installation on {{ inventory_hostname }}/{{ ansible_default_ipv4.address }}

- name: copy updated cassandra.yaml to remote nodes
  template:
        src: cassandra.yaml
        dest: /etc/dse/cassandra/cassandra.yaml
        mode: 0644

- name: copy updated dse file to remote nodes
  template:
        src: dse
        dest: /etc/default/dse
        mode: 0755

- name: start dse node
  shell: service dse start
  args:
        warn: false
  notify: 
        - fetch nodetool status
        - print nodetool status
- debug:
        msg: started dse {{ dse_version  }} on {{ inventory_hostname }}/{{ ansible_default_ipv4.address }}

- name: confirm dse start
  wait_for:
        host={{ ansible_host }}
        port={{ dse_native_transport_port }}
        timeout=60
  register: waitfor
- debug:
        msg: port check failed = {{ waitfor['failed'] }}
